import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';

const read = (path: string) => readFileSync(path, 'utf8');
const expectNoDebugIdentifiers = (text: string) => {
    expect(text).not.toContain('public/data');
    expect(text).not.toContain('dialogueId');
    expect(text).not.toContain('nodeId');
    expect(text).not.toContain('.json');
};

describe('expedition UI Chinese copy', () => {
    it('uses Chinese player-facing labels in the expedition entry scene', () => {
        const scene = read('src/game/scenes/expedition/ExpeditionScene.ts');
        const model = read('src/game/scenes/expedition/entryFlowModel.ts');
        const sceneCopy = `${scene}\n${model}`;

        expect(sceneCopy).toContain('大地图 /');
        expect(sceneCopy).toContain('返回大地图');
        expect(sceneCopy).toContain('首层：');
        expect(sceneCopy).toContain('进入秘境');
        expect(sceneCopy).toContain('点按任意处或按 Enter / Space 继续。');
        expect(sceneCopy).toContain('出发');
        expect(sceneCopy).toContain('带入已锁定');
        expect(sceneCopy).not.toContain('路线简报');
        expect(sceneCopy).not.toContain('分层速览');
        expect(sceneCopy).not.toContain('层路线');
        expect(sceneCopy).not.toContain('开局');
        expect(sceneCopy).not.toContain('远征准备');
        expect(sceneCopy).not.toContain('卡组管理');
        expect(sceneCopy).not.toContain('可返回准备');
        expect(sceneCopy).not.toContain('可出发');
        expect(sceneCopy).not.toContain('当前操作：选定带入');
        expect(sceneCopy).not.toContain('当前操作：整理卡组');
        expect(sceneCopy).not.toContain('当前带入可直接确认出发');
        expect(sceneCopy).not.toContain('完成调整后按返回回到远征准备');
        expect(sceneCopy).not.toContain('补齐带入条件后按返回回到远征准备');
        expect(sceneCopy).not.toContain('继续进入秘境');
        expect(sceneCopy).not.toContain('完成后按返回回到远征准备');
        expect(sceneCopy).not.toContain('确认路线与带入');
        expect(sceneCopy).not.toContain('已备好，从');
        expect(sceneCopy).not.toContain('先看：');
        expect(sceneCopy).not.toContain('步骤 1 / 2');
        expect(sceneCopy).not.toContain('步骤 2 / 2');
        expect(sceneCopy).not.toContain('可返回确认');
        expect(sceneCopy).not.toContain('调整后返回准备');
        expect(sceneCopy).not.toContain('补齐后返回准备');
        expect(sceneCopy).not.toContain('可直接出发');
        expect(sceneCopy).not.toContain('点按任意处或按 Enter / Space 继续。首层提示会保留。');
        expect(sceneCopy).not.toContain('点按任意处或按 Enter / Space 继续；首层视图会保留路线与带入提示。');
        expect(sceneCopy).not.toContain('出发确认');
        expect(sceneCopy).not.toContain('出发提示');
        expect(sceneCopy).not.toContain('抵达提示');
        expect(sceneCopy).not.toContain('入口：');
        expect(sceneCopy).not.toContain('收官');
        expect(sceneCopy).not.toContain('Phase 01 · Expedition Entry Flow');
    });

    it('uses Chinese loadout labels in the preparation panel', () => {
        const panel = read('src/game/ui/expedition/PreparationPanel.ts');
        const model = read('src/game/scenes/expedition/entryFlowModel.ts');
        const loadoutCopy = `${panel}\n${model}`;

        expect(panel).toContain('出发前确认');
        expect(panel).toContain('能出发就确认；不能就管理卡组。');
        expect(panel).toContain('管理卡组');
        expect(loadoutCopy).toContain('卡组符合要求，可以带入秘境。');
        expect(loadoutCopy).toContain('卡组数量不足');
        expect(loadoutCopy).toContain('卡组数量超限');
        expect(panel).toContain('当前带入');
        expect(loadoutCopy).toContain('卡组总览');
        expect(panel).toContain('当前阻塞');
        expect(panel).toContain('主操作');
        expect(panel).toContain('快捷键：Enter 主操作 · M 管理卡组');
        expect(panel).toContain('确认带入并出发');
        expect(panel).toContain('暂不可确认带入');
        expect(panel).toContain('去管理卡组补足');
        expect(panel).toContain('现在可以直接确认带入并进入秘境。');
        expect(panel).toContain('带入清单');
        expect(loadoutCopy).toContain('大地图 /');
        expect(loadoutCopy).toContain('首层');
        expect(loadoutCopy).not.toContain('起步，先看');
        expect(loadoutCopy).not.toContain('当前阶段：确认路线并选定本次带入');
        expect(loadoutCopy).not.toContain('路线速览');
        expect(panel).not.toContain('routeBriefing');
        expect(panel).not.toContain('createRouteBriefingStrip');
        expect(panel).not.toContain('measureRouteBriefingStripHeight');
        expect(panel).not.toContain('路线简报');
        expect(panel).not.toContain('分层速览');
        expect(panel).not.toContain('开局');
        expect(panel).not.toContain('收官');
        expect(panel).not.toContain('先看当前卡组能否直接出发；需要调整时去管理卡组。');
        expect(panel).not.toContain('换卡组');
        expect(panel).not.toContain('补充明细');
        expect(panel).not.toContain('需要时再看');
        expect(panel).not.toContain('携带物资');
        expect(panel).not.toContain('卡组构成');
        expect(loadoutCopy).not.toContain('路线简报');
        expect(loadoutCopy).not.toContain('分层速览');
        expect(loadoutCopy).not.toContain('开局');
        expect(panel).toContain('物资：');
        expect(loadoutCopy).toContain('件道具');
        expect(panel).toContain('灵石');
        expect(panel).not.toContain('第一阶段暂不开放卡组构筑');
        expect(panel).not.toContain('Starter Deck');
        expect(panel).not.toContain('Starter Items');
        expect(panel).not.toContain('spiritStones：');
    });

    it('uses Chinese labels in the deck workshop', () => {
        const panel = read('src/game/ui/deckbuilder/DeckManagementPanel.ts');
        const model = read('src/game/scenes/expedition/entryFlowModel.ts');
        const deckManagerCopy = `${panel}\n${model}`;

        expect(panel).toContain('返回远征准备');
        expect(panel).toContain('新建卡组');
        expect(panel).toContain('重命名');
        expect(panel).toContain('储 物 袋');
        expect(panel).toContain('搜索名称或编号');
        expect(panel).toContain('仅有库存');
        expect(panel).toContain('含无库存');
        expect(panel).toContain('左键加入 · 右键移出');
        expect(panel).toContain('还差');
        expect(panel).toContain('卡组合格，可以出发');
        expect(panel).toContain('卡组已满');
        expect(panel).toContain('同名卡最多带');
        expect(panel).toContain('储物袋里没有更多了');
        expect(panel).toContain('至少保留一套卡组');
        expect(panel).toContain('库存不足');
        expect(deckManagerCopy).toContain('大地图 /');
        expect(deckManagerCopy).not.toContain('整理时留意');
        expect(deckManagerCopy).not.toContain('当前阶段：整理卡组并返回远征准备');
        expect(panel).not.toContain('路线：');
        expect(panel).not.toContain('Return to Expedition Prep');
        expect(panel).not.toContain('Exit summary');
        expect(panel).not.toContain('Extra Deck');
    });

    it('uses Chinese run HUD labels', () => {
        const hud = read('src/game/ui/expedition/RunHud.ts');
        const model = read('src/game/scenes/expedition/entryFlowModel.ts');
        const hudCopy = `${hud}\n${model}`;

        expect(hud).toContain('当前节点：');
        expect(hud).toContain('携带卡牌：0');
        expect(hud).toContain('携带道具：0');
        expect(hud).toContain('灵石：0');
        expect(hudCopy).toContain('抵达');
        expect(hudCopy).toContain('首层已高亮');
        expect(hudCopy).toContain('带入已锁定');
        expect(hudCopy).not.toContain('首层分路已高亮；点按节点后收起。');
        expect(hudCopy).not.toContain('首个分路已高亮；点按节点后收起此提示。');
        expect(hudCopy).not.toContain('抵达提示');
        expect(hudCopy).not.toContain('带入：');
        expect(hud).not.toContain("'carriedDeck: 0'");
        expect(hud).not.toContain("'carriedItems: 0'");
        expect(hud).not.toContain("'spiritStones: 0'");
        expect(hud).not.toContain('`carriedDeck: ${carriedDeckCount}`');
        expect(hud).not.toContain('`carriedItems: ${carriedItemCount}`');
        expect(hud).not.toContain('`spiritStones: ${spiritStones}`');
        expectNoDebugIdentifiers(hud);
    });
});
