import type Phaser from 'phaser';
import { INK } from './palette';
import { Pix, bake } from './pix';

/**
 * 11x11 pixel icons. Key: o = ink outline, a = main, b = light, c = shade, w = highlight, r = accent.
 * Each icon names its own colours so it reads at a glance on any panel.
 */
type IconDef = { rows: string[]; a: number; b: number; c: number; r?: number };

const ICONS = {
    heart: { a: INK.cinnabar, b: INK.vermilion, c: INK.wine, rows: [
        '.oo...oo...',
        'obbo.oaao..',
        'obwaoaaaco.',
        'obaaaaaaco.',
        'oaaaaaaaco.',
        '.oaaaaacco.',
        '..oaaacco..',
        '...oacco...',
        '....oco....',
        '.....o.....',
        '...........'] },
    stone: { a: INK.teal, b: INK.spirit, c: INK.jade, rows: [
        '....ooo....',
        '...obbao...',
        '..obwbaao..',
        '.obbbaaaco.',
        'obbbaaaacco',
        '.oaaaaacco.',
        '..oaaacco..',
        '...oacco...',
        '....oco....',
        '.....o.....',
        '...........'] },
    qi: { a: INK.gold, b: INK.paper, c: INK.amber, rows: [
        '......ooo..',
        '.....obao..',
        '....obaao..',
        '...obaao...',
        '..obaaaooo.',
        '.oooobaaco.',
        '....obaco..',
        '...obaco...',
        '..obcoo....',
        '..oco......',
        '..oo.......'] },
    card: { a: INK.bone, b: INK.paper, c: INK.clay, r: INK.cinnabar, rows: [
        '.ooooooo...',
        '.obbbbbao..',
        '.obrrrbao..',
        '.obrwrbao..',
        '.obrrrbao..',
        '.obbbbbao..',
        '.obaaaaao..',
        '.obcccaao..',
        '.oaaaaaco..',
        '.ooooooo...',
        '...........'] },
    deck: { a: INK.bone, b: INK.paper, c: INK.clay, r: INK.cinnabar, rows: [
        '...ooooooo.',
        '..oobbbbbo.',
        '.oboooooooo',
        '.obobbbbbao',
        'oobobrrrbao',
        'obobbrwrbao',
        'obobbrrrbao',
        'obobbbbbbao',
        'oboaaaaaaco',
        'oooooooooo.',
        '...........'] },
    sword: { a: INK.haze, b: INK.paper, c: INK.mist, r: INK.gold, rows: [
        '........oo.',
        '.......obo.',
        '......obao.',
        '.....obao..',
        '.oo.obao...',
        '.oroobao...',
        '..orrao....',
        '..oorro....',
        '.ooo.oro...',
        'obo...oo...',
        'oo.........'] },
    shield: { a: INK.dusk, b: INK.haze, c: INK.slate, r: INK.gold, rows: [
        '.ooooooooo.',
        '.obbbrbaao.',
        '.obbbrbaao.',
        '.orrrrrrro.',
        '.obaarcaco.',
        '.oaaarcaco.',
        '..oaarcco..',
        '..oaaacco..',
        '...oaaco...',
        '....oco....',
        '.....o.....'] },
    scroll: { a: INK.bone, b: INK.paper, c: INK.clay, r: INK.cinnabar, rows: [
        '.ooooooooo.',
        'orrrrrrrrro',
        '.obbbbbbao.',
        '.obcccccao.',
        '.obbbbbbao.',
        '.obcccccao.',
        '.obbbbbbao.',
        '.obccccaao.',
        '.oaaaaaaao.',
        'orrrrrrrrro',
        '.ooooooooo.'] },
    map: { a: INK.bone, b: INK.paper, c: INK.clay, r: INK.cinnabar, rows: [
        'ooo..ooo...',
        'obboobbooo.',
        'obbbobbbbao',
        'obrbobbbbao',
        'obbrobcbbao',
        'obbbrbbcbao',
        'obbbobbbrao',
        'obbbobbbbro',
        'oaaaoaaaaao',
        '.oooooooooo',
        '...........'] },
    back: { a: INK.bone, b: INK.paper, c: INK.clay, rows: [
        '...........',
        '....oo.....',
        '...obo.....',
        '..obbooooo.',
        '.obbbbbbbao',
        'obbbbbbbbao',
        '.oaaaaaaaco',
        '..oaaooooo.',
        '...oao.....',
        '....oo.....',
        '...........'] },
    bag: { a: INK.clay, b: INK.skin, c: INK.bark, r: INK.gold, rows: [
        '...ooooo...',
        '...orrro...',
        '....oao....',
        '..oobaaoo..',
        '.obbbaaaco.',
        'obbwbaaaaco',
        'obbbaaaaaco',
        'obaaaaaaaco',
        'oaaaaaaacco',
        '.oaaaaccco.',
        '..ooooooo..'] },
    skull: { a: INK.bone, b: INK.paper, c: INK.ash, rows: [
        '..ooooooo..',
        '.obbbbbbao.',
        'obbbbbbbaao',
        'obooobooocо',
        'oboooboooco',
        'obbbbobbbco',
        '.oaaaaaaco.',
        '..oaoaoco..',
        '..oaoaoco..',
        '...ooooo...',
        '...........'] },
    book: { a: INK.cinnabar, b: INK.vermilion, c: INK.wine, r: INK.bone, rows: [
        '.oooooooo..',
        'obbbbbbbao.',
        'obrrrrrbao.',
        'obbbbbbbao.',
        'obrrrrrbao.',
        'obbbbbbbao.',
        'oaaaaaaaao.',
        'oaaaaaaacoo',
        'orrrrrrrrro',
        '.oooooooooo',
        '...........'] },
    close: { a: INK.bone, b: INK.paper, c: INK.clay, rows: [
        'oo.......oo',
        'obo.....obo',
        '.obo...obo.',
        '..obo.obo..',
        '...obobo...',
        '....obo....',
        '...obaco...',
        '..obo.oco..',
        '.obo...oco.',
        'obo.....oco',
        'oo.......oo'] },
    fast: { a: INK.gold, b: INK.paper, c: INK.amber, rows: [
        '...........',
        'oo...oo....',
        'obo..obo...',
        'obbo.obbo..',
        'obbbooabbo.',
        'obbbbobbbbo',
        'oaaacoaaaco',
        'oacco.acco.',
        'oco..oco...',
        'oo...oo....',
        '...........'] },
    eye: { a: INK.bone, b: INK.paper, c: INK.clay, r: INK.ink, rows: [
        '...........',
        '...ooooo...',
        '.oobbbbboo.',
        'obbboooaaao',
        'obbooroocao',
        'obboorrocao',
        '.oaaoooaco.',
        '..oaaaaco..',
        '...ooooo...',
        '...........',
        '...........'] },
    pill: { a: INK.amber, b: INK.gold, c: INK.clay, r: INK.cinnabar, rows: [
        '...........',
        '....ooo....',
        '..oobbaoo..',
        '.obbwbaaao.',
        '.obbbbaaao.',
        'orrrrrrrrro',
        '.oaaaaaaco.',
        '.oaaaaacco.',
        '..oocccoo..',
        '....ooo....',
        '...........'] },
    talisman: { a: INK.gold, b: INK.paper, c: INK.amber, r: INK.cinnabar, rows: [
        '..ooooooo..',
        '..obbbbao..',
        '..obrrbao..',
        '..obbrbao..',
        '..obrrbao..',
        '..obrbbao..',
        '..obrrbao..',
        '..obbbbao..',
        '..oaaaaco..',
        '..ooooooo..',
        '...o.o.o...'] },
    bell: { a: INK.teal, b: INK.spirit, c: INK.jade, r: INK.gold, rows: [
        '....ooo....',
        '....oro....',
        '...ooooo...',
        '..obbaaao..',
        '..obraraco.',
        '..obbaaaco.',
        '.obbraracco',
        '.obbaaaacco',
        'oooooooooo.',
        '....oro....',
        '....ooo....'] },
    mountain: { a: INK.dusk, b: INK.bone, c: INK.slate, r: INK.teal, rows: [
        '...........',
        '....oo.....',
        '...obbo....',
        '..obbaao.o.',
        '..obaaaoobo',
        '.obaaaacoao',
        '.oaaaaaacao',
        'oaaacaacaco',
        'orrrrrrrrro',
        'ooooooooooo',
        '...........'] },
    star: { a: INK.gold, b: INK.paper, c: INK.amber, rows: [
        '.....o.....',
        '....obo....',
        '....obo....',
        'oooobaaoooo',
        'obbbbaaaaco',
        '.oobbaaacoo',
        '..obaaaco..',
        '..obaocao..',
        '.obao.ocao.',
        '.oao...oco.',
        '.oo.....oo.'] },
    flag: { a: INK.cinnabar, b: INK.vermilion, c: INK.wine, r: INK.bark, rows: [
        'oo.........',
        'orooooooo..',
        'orobbbbbbo.',
        'orobbwbbao.',
        'orobbbbaao.',
        'oroaaaaaco.',
        'orooooooo..',
        'oro........',
        'oro........',
        'oro........',
        'ooo........'] },
    gear: { a: INK.mist, b: INK.haze, c: INK.dusk, rows: [
        '....ooo....',
        '.oo.obo.oo.',
        '.obooboobo.',
        '..obbbbao..',
        'oobboooaaoo',
        'obbao.oaaco',
        'oobaoooacoo',
        '..oaaaaco..',
        '.oaooacoco.',
        '.oo.oco.oo.',
        '....ooo....'] },
    lock: { a: INK.gold, b: INK.paper, c: INK.amber, r: INK.ink, rows: [
        '...ooooo...',
        '..oo...oo..',
        '..o.....o..',
        '..o.....o..',
        '.ooooooooo.',
        '.obbbbbaao.',
        '.obbborbao.',
        '.obbborbao.',
        '.oaaaaaaco.',
        '.ooooooooo.',
        '...........'] },
    fire: { a: INK.vermilion, b: INK.gold, c: INK.cinnabar, rows: [
        '.....o.....',
        '....oao....',
        '...oaao.o..',
        '..oaabaoao.',
        '.oaabbaaao.',
        '.oabbbbaaco',
        'oaabbwbaaco',
        'oaabbbbaaco',
        '.oaabbaacо.',
        '..ooaaacoo.',
        '....oooo...'] },
    cup: { a: INK.bone, b: INK.paper, c: INK.clay, r: INK.teal, rows: [
        '...o.o.....',
        '..o.o......',
        '...o.o.....',
        '.ooooooooo.',
        '.obrrrrraoo',
        '.obbbbbbaoo',
        '.obbbbbbaco',
        '..obbbbaoo.',
        '..oaaaaco..',
        '.ooooooooo.',
        '...........'] },
} satisfies Record<string, IconDef>;

export type PixIcon = keyof typeof ICONS;

export function iconPix(name: PixIcon): Pix {
    const d: IconDef = ICONS[name];
    const p = new Pix(11, 11);
    p.sprite(d.rows, 0, 0, { o: INK.void, a: d.a, b: d.b, c: d.c, w: INK.paper, r: d.r ?? d.c, 'о': INK.void });
    return p;
}

export function iconKey(scene: Phaser.Scene, name: PixIcon): string {
    return bake(scene, `pxi:${name}`, () => iconPix(name));
}

/** Add an icon image (art-grid scale multiplier `k`, default 1 art px per icon px). */
export function addIcon(scene: Phaser.Scene, x: number, y: number, name: PixIcon, k = 1): Phaser.GameObjects.Image {
    return scene.add.image(Math.round(x / 3) * 3, Math.round(y / 3) * 3, iconKey(scene, name)).setScale(3 * k);
}
